apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: kubernetes.io/basic-auth
stringData:
  password: root
  DB_USERNAME: root
  DB_PASSWORD: root
  DB_HOST: mysql
  DB_PORT: "3306"
  DB_DATABASE: testing
  APP_PORT: "5000"