apiVersion: v1
kind: Service
metadata:
  name: mysql-core-api-consumer
spec:
  type: NodePort
  selector:
    app: mysql-core-api-consumer
  ports:
  - port: 5000
    targetPort: 5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-core-api-consumer
spec:
  selector:
    matchLabels:
      app: mysql-core-api-consumer
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-core-api-consumer
    spec:
      containers:
      - name: mysql-core-api-consumer
        image: darwisnarvaezdev/k8s-mysql-demo:k8s
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DB_PASSWORD
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DB_PORT
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DB_DATABASE
        - name: APP_PORT
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: APP_PORT
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 5000